
package com.scriptons.crop;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CropClass", targetNamespace = "http://crop.scriptons.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CropClass {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "getNameReturn", targetNamespace = "http://crop.scriptons.com")
    @RequestWrapper(localName = "getName", targetNamespace = "http://crop.scriptons.com", className = "com.scriptons.crop.GetName")
    @ResponseWrapper(localName = "getNameResponse", targetNamespace = "http://crop.scriptons.com", className = "com.scriptons.crop.GetNameResponse")
    public String getName();

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "getAgeReturn", targetNamespace = "http://crop.scriptons.com")
    @RequestWrapper(localName = "getAge", targetNamespace = "http://crop.scriptons.com", className = "com.scriptons.crop.GetAge")
    @ResponseWrapper(localName = "getAgeResponse", targetNamespace = "http://crop.scriptons.com", className = "com.scriptons.crop.GetAgeResponse")
    public int getAge();

}
