
package com.scriptons.crop;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CropClassService", targetNamespace = "http://crop.scriptons.com", wsdlLocation = "http://localhost:8080/scripton/services/CropClass?wsdl")
public class CropClassService
    extends Service
{

    private final static URL CROPCLASSSERVICE_WSDL_LOCATION;
    private final static WebServiceException CROPCLASSSERVICE_EXCEPTION;
    private final static QName CROPCLASSSERVICE_QNAME = new QName("http://crop.scriptons.com", "CropClassService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/scripton/services/CropClass?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CROPCLASSSERVICE_WSDL_LOCATION = url;
        CROPCLASSSERVICE_EXCEPTION = e;
    }

    public CropClassService() {
        super(__getWsdlLocation(), CROPCLASSSERVICE_QNAME);
    }

    public CropClassService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CROPCLASSSERVICE_QNAME, features);
    }

    public CropClassService(URL wsdlLocation) {
        super(wsdlLocation, CROPCLASSSERVICE_QNAME);
    }

    public CropClassService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CROPCLASSSERVICE_QNAME, features);
    }

    public CropClassService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CropClassService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CropClass
     */
    @WebEndpoint(name = "CropClass")
    public CropClass getCropClass() {
        return super.getPort(new QName("http://crop.scriptons.com", "CropClass"), CropClass.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CropClass
     */
    @WebEndpoint(name = "CropClass")
    public CropClass getCropClass(WebServiceFeature... features) {
        return super.getPort(new QName("http://crop.scriptons.com", "CropClass"), CropClass.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CROPCLASSSERVICE_EXCEPTION!= null) {
            throw CROPCLASSSERVICE_EXCEPTION;
        }
        return CROPCLASSSERVICE_WSDL_LOCATION;
    }

}
